version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "1323:1323"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    # volumes:
    #   - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      timezone: ${TZ}
    ports:
      - "3306:3306"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

# volumes:
#   db_data: